services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: picpay-simplificado-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - picpay-simplificado-network

  nginx:
    image: nginx:alpine
    container_name: picpay-simplificado-nginx
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - picpay-simplificado-network

  db:
    image: mysql:8.0
    container_name: picpay-simplificado-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: picpay_simplificado
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - picpay-simplificado-db-data:/var/lib/mysql
    networks:
      - picpay-simplificado-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: picpay-simplificado-phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - picpay-simplificado-network

volumes:
  picpay-simplificado-db-data:

networks:
  picpay-simplificado-network:
    driver: bridge
